# Generated by Django 4.0.7 on 2023-02-27 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(error_messages={'unique': 'user with this email already exists.'}, max_length=254, unique=True),
        ),
    ]
