# Generated by Django 4.0.7 on 2023-02-27 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(error_messages={'unique': 'This field must be unique.'}, max_length=127, unique=True),
        ),
    ]
